# Generated by Django 4.2.4 on 2023-09-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_capitulo_options_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
