# Generated by Django 4.2.4 on 2023-09-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_pagina_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='livro',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='livro.livro'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='titulo',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='capitulo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='livro.capitulo'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='conteudo',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='numero',
            field=models.PositiveIntegerField(blank=True, default=False, null=True),
        ),
    ]
