# Generated by Django 4.2.4 on 2023-09-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_remove_autor_livros'),
        ('livro', '0004_alter_capitulo_livro_alter_capitulo_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contrib.autor'),
            preserve_default=False,
        ),
    ]
