# Generated by Django 4.2.4 on 2023-09-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_remove_autor_livros'),
        ('livro', '0005_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contrib.autor'),
        ),
    ]
