# Generated by Django 4.2.4 on 2023-09-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0004_alter_capitulo_livro_alter_capitulo_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(null=True)),
                ('livros', models.ManyToManyField(to='livro.livro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
