# Generated by Django 4.2.4 on 2023-09-30 17:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_alter_capitulo_livro_alter_capitulo_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrib', '0002_alter_atutor_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atutor',
            new_name='Autor',
        ),
    ]
