# Generated by Django 4.2.4 on 2023-09-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_rename_atutor_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='livros',
        ),
    ]
